adl_reg: 1
data_scale: 0.005
dataset_type: image
dec_size:
- 1024
- 512
- 1024
dist_thresh: 100
enc_dest_size:
- 8
- 16
enc_latent_size:
- 8
- 50
enc_past_size:
- 512
- 256
fdim: 16
future_length: 12
gpu_index: 0
kld_reg: 1
learning_rate: 0.0000003
mu: 0
n_values: 20
normalize_type: shift_origin
num_epochs: 600
num_workers: 0
past_length: 8
sigma: 1.3
test_b_size: 512
time_thresh: 0
train_b_size: 512
zdim: 16

input_size: 4
embedding_size: 64
rnn_size: 256
output_size: 16
enc_size_nsp:
- 64
- 256
dec_size_nsp:
- 512
- 256
- 512




